[settings]
lockfile = true

[tools]
deno = "latest"
hk = "latest"
pkl = "latest"

[tasks.install-cli]
description = "Install the CLI"
usage = 'flag "--root <root>"'
run = [
    "deno install -A --global --force --config deno.jsonc --name konaste --root \"${usage_root:-$HOME/.deno}\" src/main.ts",
]

[tasks.check]
description = "Run all checks"
run = [
    "deno lint",
    "deno fmt --check",
    "deno check",
    "pkl eval hk.pkl >/dev/null",
]

[tasks.build]
description = "Build the CLI binary"
usage = 'flag "--arch <arch>" default="x86_64-unknown-linux-gnu"'
run = [
    "deno compile -A --target ${usage_arch?} -o dist/konaste-${usage_arch?} src/main.ts",
]

[tasks.prepare-release]
description = "Prepare for release"
usage = 'flag "--version <version>"'
run = [
    "deno install",
    "printf '\"%s\"\\n' \"${usage_version:?}\" > version.json",
    "mise run build --arch=x86_64-unknown-linux-gnu",
    "mise run build --arch=aarch64-unknown-linux-gnu",
]
